name: tuomo_workbench
description: 拓墨离线优先写作与多站点发布工作台
publish_to: none
version: 0.1.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  flutter_secure_storage: ^10.3.2
  archive: ^4.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
