import type { Article } from '../domain/article.ts';
import { DomainError } from '../domain/errors.ts';
import { contentHash } from '../domain/values.ts';
import type { CmsPost, CmsPostGateway, BindingStore, ArticleRepository } from './ports.ts';
import type { CmsSite } from '../domain/site.ts';

export type CmsSyncState = 'inSync' | 'pushRequired' | 'pullRequired' | 'conflict' | 'missing';
export type CmsSyncComparison = { state: CmsSyncState; articleId: string; siteId: string; localHash: string; remoteHash?: string; baseHash?: string; remote?: CmsPost };
export type ConflictResolution = 'local' | 'remote' | 'merged';
function canonicalArticleHash(article: Article): string { return contentHash({ title: article.title, markdown: article.body, slug: article.metadata.slug, tags: article.metadata.tags, categories: article.metadata.categories, status: article.published ? 'published' : 'draft', date: article.scheduleAt ?? article.updatedAt }); }

export function threeWayMerge(base: string, local: string, remote: string): { clean: boolean; content: string } { if (local === remote) return { clean: true, content: local }; if (local === base) return { clean: true, content: remote }; if (remote === base) return { clean: true, content: local }; const baseLines = base.split('\n'); const localLines = local.split('\n'); const remoteLines = remote.split('\n'); const max = Math.max(baseLines.length, localLines.length, remoteLines.length); const output: string[] = []; let clean = true; for (let index = 0; index < max; index++) { const b = baseLines[index] ?? ''; const l = localLines[index] ?? ''; const r = remoteLines[index] ?? ''; if (l === r) output.push(l); else if (l === b) output.push(r); else if (r === b) output.push(l); else { clean = false; output.push('<<<<<<< LOCAL', l, '=======', r, '>>>>>>> REMOTE'); } } return { clean, content: output.join('\n') }; }

export class CmsSyncUseCase {
  private readonly articles: ArticleRepository;
  private readonly gateway: CmsPostGateway;
  private readonly bindings: BindingStore;
  constructor(articles: ArticleRepository, gateway: CmsPostGateway, bindings: BindingStore) { this.articles = articles; this.gateway = gateway; this.bindings = bindings; }
  async compare(articleId: string, site: CmsSite, remote?: CmsPost): Promise<CmsSyncComparison> { const article = await this.articles.get(articleId); if (!article) throw new DomainError('notFound', `Article not found: ${articleId}`); const binding = await this.bindings.get(site.id, articleId); const value = remote ?? (binding?.remoteId ? (await this.gateway.list(site, {})).find((post) => post.id === binding.remoteId) : undefined); const localHash = canonicalArticleHash(article); const remoteHash = value ? contentHash({ title: value.title, markdown: value.markdown, slug: value.slug, tags: value.tags, categories: value.categories, status: value.status, date: value.date }) : undefined; if (!value) return { state: binding ? 'missing' : 'pushRequired', articleId, siteId: site.id, localHash, remoteHash, baseHash: binding?.baseContentHash }; if (localHash === binding?.baseContentHash && remoteHash === binding.baseContentHash) return { state: 'inSync', articleId, siteId: site.id, localHash, remoteHash, baseHash: binding.baseContentHash, remote: value }; if (localHash === binding?.baseContentHash) return { state: 'pullRequired', articleId, siteId: site.id, localHash, remoteHash, baseHash: binding.baseContentHash, remote: value }; if (remoteHash === binding?.baseContentHash) return { state: 'pushRequired', articleId, siteId: site.id, localHash, remoteHash, baseHash: binding.baseContentHash, remote: value }; return { state: binding ? 'conflict' : 'pushRequired', articleId, siteId: site.id, localHash, remoteHash, baseHash: binding?.baseContentHash, remote: value }; }
  async resolve(comparison: CmsSyncComparison, site: CmsSite, resolution: ConflictResolution, baseMarkdown = ''): Promise<Article> { const article = await this.articles.get(comparison.articleId); if (!article) throw new DomainError('notFound', 'Article not found'); if (!comparison.remote && resolution === 'remote') throw new DomainError('notFound', 'Remote post is missing'); const remote = comparison.remote; let body = article.body; let title = article.title; if (resolution === 'remote' && remote) { body = remote.markdown; title = remote.title; } else if (resolution === 'merged' && remote) { const merged = threeWayMerge(baseMarkdown, article.body, remote.markdown); if (!merged.clean) throw new DomainError('conflict', 'Manual merge is required', { content: merged.content }); body = merged.content; } return { ...article, title, body, localRevision: article.localRevision + 1, updatedAt: new Date().toISOString() }; }
}
